[HIPIFY][FILE][tests][Windows][fix] Fix the `cufile2hipfile.cu` test failed on `Windows` only (#2431)
[Synopsis]
+ Compilation error: `error : expression is not assignable`:
  - CUfileStatus_t STATUS_PENDING = CUFILE_PENDING;
  - CUfileStatus_t STATUS_TIMEOUT = CUFILE_TIMEOUT;

[Root Cause]
+ `STATUS_PENDING` and `STATUS_TIMEOUT` are defined in `winnt.h` as:
   - #define STATUS_TIMEOUT                   ((DWORD   )0x00000102L)
   - #define STATUS_PENDING                   ((DWORD   )0x00000103L)
+ Thus assignment error

[Solution]
+ Renaming the conflicting variables of the `CUfileStatus_t` type in the test itself
+ [ToDo] Rename all the rest `STATUS_*` variables