[HIPIFY][fix] Fix building by old C++ compilers
For instance, compiling hipify-clang by Visual Studio 2015 leads to the following error:
`error C2440: 'initializing': cannot convert from 'initializer list' to 'std::map<llvm::StringRef,cudaAPIversions,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>'`