[HIPIFY][BLAS] Satisfy CUDA 11.7.1 restriction
[Restriction]
+ If both `cublas.h` and `cublas_v2.h` are included the following error occurs:
  `cublas.h(61,2): error: "It is an error to include both cublas.h and cublas_v2.h"`

[Solution]
+ Swap `cublas_v2.h` and `cublas.h` includes if `cublas_v2.h` goes first
+ Actually, CUDA error message is misleading: erroneous to include `cublas_v2.h` before `cublas.h` only;
+ On the other hand, including them both is correct and only possible, when v1 and v2 APIs are needed to be used, cause
  not every API from `cublas.h` has a corresponding v2 analogue in `cublas_v2.h`