[HIPIFY][#1021][build][MSVS][fix][partial] Fix for `error C2365` occurred on VS 2022 with ToT clang 18.0.0git
[Synopsis]
+ Root cause is LLVM's change [Driver] Refactor to use llvm Option's new Visibility flags (SHA-1: 9478f661c26fbc22491218477917df5d8d73c51c)
+ But LLVM/clang itself is built correctly by VS 2022

[Solution]
+ Explicit setting of `UseStandardPreprocessor` (`/Zc:preprocessor`) eliminates the preprocessor's macro redefinition error

[ToDo]
+ Check hipify-clang builds by MSVS 2017 and 2019 against ToT LLVM (18.0.0git), LLVM 17.0.0-preview, and LLVM 16.0.x